"""Add failure risks and source citations

Revision ID: 2fcb9cc8a022
Revises: c85ebddedb3c
Create Date: 2026-07-02 01:07:24.889617
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2fcb9cc8a022'
down_revision: Union[str, None] = 'c85ebddedb3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_citations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('field_referenced', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_citations_project_id'), 'source_citations', ['project_id'], unique=False)
    op.create_table('failure_risks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_brief_id', sa.UUID(), nullable=False),
    sa.Column('precedent_name', sa.String(), nullable=False),
    sa.Column('similarity_reason', sa.String(), nullable=False),
    sa.Column('mitigation_suggestion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_brief_id'], ['brand_briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_risks_brand_brief_id'), 'failure_risks', ['brand_brief_id'], unique=False)
    op.add_column('intake_briefs', sa.Column('brand_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_briefs', 'brand_name')
    op.drop_index(op.f('ix_failure_risks_brand_brief_id'), table_name='failure_risks')
    op.drop_table('failure_risks')
    op.drop_index(op.f('ix_source_citations_project_id'), table_name='source_citations')
    op.drop_table('source_citations')
    # ### end Alembic commands ###
