"""Add IntakeBrief model

Revision ID: 92ec85f91e4e
Revises: d096c516f68d
Create Date: 2026-07-01 23:01:17.157429
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92ec85f91e4e'
down_revision: Union[str, None] = 'd096c516f68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_briefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('problem_statement', sa.String(), nullable=True),
    sa.Column('target_user', sa.String(), nullable=True),
    sa.Column('known_competitors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('budget_constraint', sa.String(), nullable=True),
    sa.Column('timeline_constraint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_briefs_project_id'), 'intake_briefs', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_briefs_project_id'), table_name='intake_briefs')
    op.drop_table('intake_briefs')
    # ### end Alembic commands ###
