"""add_definition_engine_models

Revision ID: c85ebddedb3c
Revises: 92ec85f91e4e
Create Date: 2026-07-01 23:38:48.042008
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c85ebddedb3c'
down_revision: Union[str, None] = '92ec85f91e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_briefs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('whitespace_summary', sa.String(), nullable=False),
    sa.Column('price_tier_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('psychographic_target', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_credibility_score', sa.Numeric(), nullable=True),
    sa.Column('recommended_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_briefs_project_id'), 'brand_briefs', ['project_id'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reach', sa.Numeric(), nullable=False),
    sa.Column('impact', sa.Numeric(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('effort', sa.Numeric(), nullable=True),
    sa.Column('rice_score', sa.Numeric(), nullable=True),
    sa.Column('priority_label', sa.String(), nullable=False),
    sa.Column('moscow_label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goals', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pain_points', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_project_id'), 'personas', ['project_id'], unique=False)
    op.create_table('prds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('content_markdown', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prds_project_id'), 'prds', ['project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prds_project_id'), table_name='prds')
    op.drop_table('prds')
    op.drop_index(op.f('ix_personas_project_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_brand_briefs_project_id'), table_name='brand_briefs')
    op.drop_table('brand_briefs')
    # ### end Alembic commands ###
